In [183]:
import numpy as np

### 1

In [184]:
A1 = np.matrix('3 7; 5 2')
u1, s1, vt1 = np.linalg.svd(A1)
s1 = np.diag(s1)
u1, s1, vt1

(matrix([[-0.85065081, -0.52573111],
         [-0.52573111,  0.85065081]]), array([[8.71337969, 0.        ],
        [0.        , 3.32821489]]), matrix([[-0.59455781, -0.80405286],
         [ 0.80405286, -0.59455781]]))

In [185]:
u1.shape, s1.shape, vt1.shape

((2, 2), (2, 2), (2, 2))

In [186]:
u1*s1*vt1

matrix([[3., 7.],
        [5., 2.]])

In [187]:
np.allclose(A1, _)

True

### 2

In [188]:
A2 = np.matrix('0 1 3; 2 3 1; 0 1 0')
u2, s2, vt2 = np.linalg.svd(A2)
s2 = np.diag(s2)
u2, s2, vt2

(matrix([[-0.56667985,  0.82277903,  0.04368772],
         [-0.80674247, -0.54329657, -0.23236915],
         [-0.16745308, -0.16692366,  0.97164601]]),
 array([[4.34019342, 0.        , 0.        ],
        [0.        , 2.41561763, 0.        ],
        [0.        , 0.        , 0.57228713]]),
 matrix([[-0.37175416, -0.72677875, -0.5775738 ],
         [-0.44982001, -0.40322372,  0.79691442],
         [-0.81207192,  0.5560605 , -0.17701953]]))

In [189]:
u2.shape, s2.shape, vt2.shape

((3, 3), (3, 3), (3, 3))

In [190]:
u2*s2*vt2

matrix([[-2.07793506e-16,  1.00000000e+00,  3.00000000e+00],
        [ 2.00000000e+00,  3.00000000e+00,  1.00000000e+00],
        [-2.74065170e-17,  1.00000000e+00, -1.43523152e-16]])

In [191]:
np.allclose(A2, _)

True

### 3

In [192]:
A3 = np.matrix('5 7 6 4 2; 1 3 4 1 3; 3 4 5 4 1')
u3, s3, vt3 = np.linalg.svd(A3)
s3_f = np.zeros(A3.shape)
s3_f[:A3.shape[0], :A3.shape[0]] = np.diag(s3)
s3 = s3_f
u3, s3, vt3

(matrix([[-0.75927897,  0.23445293, -0.60706446],
         [-0.3639706 , -0.92629427,  0.09749016],
         [-0.53946348,  0.29497584,  0.78864974]]),
 array([[14.94713352,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  2.72739944,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.46440832,  0.        ,  0.        ]]),
 matrix([[-0.38661298, -0.57300074, -0.58264507, -0.37190679, -0.21073828],
         [ 0.41464331,  0.01546935, -0.3019654 ,  0.43683401, -0.73879941],
         [-0.39052151, -0.5479222 ,  0.47174175,  0.56256936, -0.09082761],
         [-0.43720626,  0.36725326, -0.53062765,  0.5481159 ,  0.30328039],
         [ 0.5787443 , -0.48614521, -0.2554127 ,  0.23226293,  0.55635974]]))

In [193]:
u3.shape, s3.shape, vt3.shape

((3, 3), (3, 5), (5, 5))

In [194]:
u3*s3*vt3

matrix([[5., 7., 6., 4., 2.],
        [1., 3., 4., 1., 3.],
        [3., 4., 5., 4., 1.]])

In [195]:
np.allclose(A3, _)

True